name: Build and Publish to NuGet

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # === MessageInvoker.Core ===
      - name: Restore MessageInvoker.AzureServiceBus
        run: dotnet restore src/MessageInvoker.AzureServiceBus/MessageInvoker.AzureServiceBus.csproj

      - name: Build MessageInvoker.AzureServiceBus
        run: dotnet build src/MessageInvoker.AzureServiceBus/MessageInvoker.AzureServiceBus.csproj --configuration Release --no-restore

      - name: Pack MessageInvoker.Core
        run: dotnet pack src/MessageInvoker.AzureServiceBus/MessageInvoker.AzureServiceBus.csproj --configuration Release --no-build -o ./nupkgs

      # === MessageInvoker.RabbitMQ ===
      - name: Restore MessageInvoker.RabbitMQ
        run: dotnet restore src/MessageInvoker.RabbitMQ/MessageInvoker.RabbitMQ.csproj

      - name: Build MessageInvoker.RabbitMQ
        run: dotnet build src/MessageInvoker.RabbitMQ/MessageInvoker.RabbitMQ.csproj --configuration Release --no-restore

      - name: Pack MessageInvoker.RabbitMQ
        run: dotnet pack src/MessageInvoker.RabbitMQ/MessageInvoker.RabbitMQ.csproj --configuration Release --no-build -o ./nupkgs

      # === Push All .nupkg to NuGet ===
      - name: Push to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET }} --source https://api.nuget.org/v3/index.json
